### ISSUE TITLE
Exception when running riven

### ISSUE THREAD

**Issue by jsonfry** [phortx/riven#1]
When running `riven myfile.md`, `riven -o myfile.pdf myfile.md` or even just `riven` I get the following exception:

```
/Library/Ruby/Gems/2.0.0/gems/riven-1.0.0/lib/riven/markup_file.rb:15:in `public': nil is not a symbol (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/riven-1.0.0/lib/riven/markup_file.rb:15:in `<class:MarkupFile>'
	from /Library/Ruby/Gems/2.0.0/gems/riven-1.0.0/lib/riven/markup_file.rb:6:in `<module:Riven>'
	from /Library/Ruby/Gems/2.0.0/gems/riven-1.0.0/lib/riven/markup_file.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/riven-1.0.0/lib/riven/opt_parser.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/riven-1.0.0/bin/riven:7:in `<top (required)>'
	from /usr/bin/riven:23:in `load'
	from /usr/bin/riven:23:in `<main>'
```

I'm running a Mac on OS X 10.10.2

**Comment by phortx** [comment]
You need at least ruby 2.1 to run the riven gem. Sorry.

**Comment by phortx** [comment]
I've released a new [version](https://github.com/phortx/riven/releases/tag/1.0.1), which manifests this requirement in the gemspec. So it's not possible to install riven on a ruby version lower then 2.1 anymore.

I recommend you to use [RVM](http://rvm.io) in order to maintain the newest ruby version on your machine :)

Thank you for reporting.
